{
 "title": "host-monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - (\r\n  sum by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[5m]))\r\n  /\r\n  sum by (instance) (irate(windows_cpu_time_total[5m]))\r\n))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Windows exporter health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"windows\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEMORY USAGE ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1 - (windows_memory_available_bytes / windows_memory_physical_total_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * avg by (instance, volume) ((windows_logical_disk_size_bytes - windows_logical_disk_free_bytes) / windows_logical_disk_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}